name: Update JSON
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install node-fetch
      - name: Update JSON
        env:
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
        run: |
          node fetch-webflow.js
      - name: Commit and Push
        run: |
          if [ -f data.json ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add data.json
            git commit -m "Update data"
            git push
          else
            echo "data.json not found, skipping commit"
            exit 1
          fi
