name: Update JSON
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install node-fetch
      - name: Update JSON
        env:
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
        run: |
          node fetch-webflow.js || exit 1
      - name: Commit and Push
        if: success()
        run: |
          if [ -f data.json ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add data.json
            git commit -m "Update data"
            git push
          fi
